name: tarot_coach
description: "TarotCoach - L'assistant intelligent pour vos parties de Tarot français"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.4
  flutter_animate: ^4.5.2
  google_fonts: ^6.2.1
  syncfusion_flutter_pdfviewer: ^27.1.48

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/rules/
